export const GET_ISSUES = 'GET_ISSUES';
export const GET_ISSUES_PENDING = 'GET_ISSUES_PENDING';
export const GET_ISSUES_SUCCESS = 'GET_ISSUES_SUCCESS';
export const GET_ISSUES_FAILURE = 'GET_ISSUES_FAILURE';
