export const GET_JOIN_REQUESTS_PENDING = 'GET_JOIN_REQUESTS_PENDING';
export const GET_JOIN_REQUESTS = 'GET_JOIN_REQUESTS';
export const GET_JOIN_REQUESTS_SUCCESS = 'GET_JOIN_REQUESTS_SUCCESS';
export const GET_JOIN_REQUESTS_FAILURE = 'GET_JOIN_REQUESTS_FAILURE';

export const POST_JOIN_REQUEST_APPROVE_PENDING = 'POST_JOIN_REQUEST_APPROVE_PENDING';
export const POST_JOIN_REQUEST_APPROVE = 'POST_JOIN_REQUEST_APPROVE';
export const POST_JOIN_REQUEST_APPROVE_SUCCESS = 'POST_JOIN_REQUEST_APPROVE_SUCCESS';
export const POST_JOIN_REQUEST_APPROVE_FAILURE = 'POST_JOIN_REQUEST_APPROVE_FAILURE';

export const POST_JOIN_REQUEST_REJECT_PENDING = 'POST_JOIN_REQUEST_REJECT_PENDING';
export const POST_JOIN_REQUEST_REJECT = 'POST_JOIN_REQUEST_REJECT';
export const POST_JOIN_REQUEST_REJECT_SUCCESS = 'POST_JOIN_REQUEST_REJECT_SUCCESS';
export const POST_JOIN_REQUEST_REJECT_FAILURE = 'POST_JOIN_REQUEST_REJECT_FAILURE';