export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECT_PENDING = "GET_PROJECT_PENDING";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE";
