// View table
export const GET_EXAM_TABLE_DATA_PENDING = 'GET_EXAM_TABLE_DATA_PENDING';
export const GET_EXAM_TABLE_DATA = 'GET_EXAM_TABLE_DATA';
export const GET_EXAM_TABLE_DATA_SUCCESS = 'GET_EXAM_TABLE_DATA_SUCCESS';
export const GET_EXAM_TABLE_DATA_FAILURE = 'GET_EXAM_TABLE_DATA_FAILURE';

// Append new data
export const APPEND_EXAM_DATA_PENDING = 'APPEND_EXAM_DATA_PENDING';
export const APPEND_EXAM_DATA = 'APPEND_EXAM_DATA';
export const APPEND_EXAM_DATA_SUCCESS = 'APPEND_EXAM_DATA_SUCCESS';
export const APPEND_EXAM_DATA_FAILURE = 'APPEND_EXAM_DATA_FAILURE';

// Delete data
export const DELETE_EXAM_DATA_PENDING = 'DELETE_EXAM_DATA_PENDING';
export const DELETE_EXAM_DATA = 'DELETE_EXAM_DATA';
export const DELETE_EXAM_DATA_SUCCESS = 'DELETE_EXAM_DATA_SUCCESS';
export const DELETE_EXAM_DATA_FAILURE = 'DELETE_EXAM_DATA_FAILURE';

// Revise data
export const REVISE_EXAM_DATA_PENDING = 'REVISE_EXAM_DATA_PENDING';
export const REVISE_EXAM_DATA = 'REVISE_EXAM_DATA';
export const REVISE_EXAM_DATA_SUCCESS = 'REVISE_EXAM_DATA_SUCCESS';
export const REVISE_EXAM_DATA_FAILURE = 'REVISE_EXAM_DATA_FAILURE';